-- 코드를 작성해주세요
WITH YEARLY_MAX AS (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    YEAR(e.DIFFERENTIATION_DATE) AS YEAR, 
    (ym.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV, 
    e.ID
FROM ECOLI_DATA e
JOIN YEARLY_MAX ym
ON YEAR(e.DIFFERENTIATION_DATE) = ym.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
